site_name: 'MLBox'
site_description: 'Documentation site for MLBox'
site_author: 'Adhita Selvaraj <adhita.selvaraj@gmail.com>'
docs_dir: 'docs/'

nav:
  - Home: index.md
  - Getting Started: Getting Started/index.md
  - Runners: Runners/index.md

theme:
  name: 'material'

theme:
  name: material
  #logo: 'assets/android-chrome-512x512.png'
  favicon: 'assets/favicon.ico'
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Circular'
    code: 'Inconsolata'

extra_css:
  - 'assets/stylesheets/circular.css'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True
