site_name: 'MLCube'
site_description: 'Documentation site for MLCube'
site_author: '<MLPerf.org> mlcommons@googlegroups.com'
docs_dir: 'docs/'

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/index.md
    - Hello World: getting-started/hello-world.md
    - MNIST: getting-started/mnist.md
  - Tutorials:
    - How to Create an MLCube: tutorials/create-mlcube.md
  - Runners:
    - Runners: runners/index.md
    - Docker Runner: runners/docker-runner.md
    - Singularity Runner: runners/singularity-runner.md
    - SSH Runner: runners/ssh-runner.md
    - Kubernetes Runner: runners/kubernetes.md
    - GCP Runner: runners/gcp-runner.md

theme:
  name: 'material'
  favicon: 'assets/favicon.ico'
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Circular'
    code: 'Inconsolata'

extra_css:
  - 'assets/stylesheets/circular.css'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True
