# Schema
schema_version: 1.0.0
schema_type: mlbox_task

# Task Inputs
inputs: []

# Task Outputs
outputs:
        - name: data_dir
          type: directory

        - name: log_dir
          type: directory
